# Generated by Django 2.1 on 2019-07-07 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='storegrade',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='author',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storegrade',
            name='author',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storegrade',
            name='grade_comment',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='comment',
            field=models.TextField(blank=True, default='반갑습니다.', max_length=200, verbose_name='소개'),
        ),
    ]
