# Generated by Django 2.1 on 2019-07-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storegrade',
            name='store_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.Item'),
        ),
        migrations.AddField(
            model_name='storegrade',
            name='store_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreProfile'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.QuestionComment'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='store_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreProfile'),
        ),
    ]
