# Generated by Django 2.1 on 2019-07-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='storegrade',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='storegrade',
            name='grade_comment',
            field=models.TextField(max_length=250),
        ),
    ]
