# Generated by Django 2.1 on 2019-05-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190529_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='comment',
            field=models.CharField(blank=True, default='반갑습니다.', max_length=200, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
