# Generated by Django 2.1 on 2019-05-30 07:24

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190529_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile/storephoto'),
        ),
    ]
