# Generated by Django 2.1 on 2019-06-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190602_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='store.QuestionComment'),
        ),
    ]
