# Generated by Django 2.1 on 2019-06-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190604_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storegrade',
            name='grade',
        ),
    ]
