# Generated by Django 2.1 on 2019-06-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_storegrade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='storegrade',
            name='rasting',
            field=models.CharField(choices=[('0', '☆☆☆☆☆'), ('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], db_index=True, default=0, max_length=10),
        ),
    ]
