# Generated by Django 2.1 on 2019-06-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storegrade_rasting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storegrade',
            old_name='rasting',
            new_name='rating',
        ),
    ]
