# Generated by Django 2.1 on 2019-06-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
        ('store', '0011_auto_20190604_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='storegrade',
            name='store_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='trade.Item'),
            preserve_default=False,
        ),
    ]
