# Generated by Django 2.1 on 2019-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190604_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
