# Generated by Django 2.1 on 2019-06-06 19:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_storegrade_store_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile/default/noimage.png', null=True, upload_to='profile/storephoto'),
        ),
    ]
