# Generated by Django 2.1 on 2019-06-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190606_2112'),
        ('store', '0013_auto_20190606_1909'),
    ]

    operations = [
    ]
