language: python
python:
- 3.6.8
notifications:
  slack:
    secure: 0AeFs52dM8hxhzBVNDwLRyxNfUCV6aX5mQCWNA1UMXNFjHQd4ITqmqDnpNdnj+c007VLheTss+GpJQmhKHFrkvXgRTiVWcXrK3Og0MLG5R9dyCGWS5iI3xmkR+D4GRsV7J9jPRiKVV/7UimrR1co6FkK2xLqEbWUBjV3bH8kWb2JEqncHRMPVvox2DIOu/w2JEj9TfM8X601yOhRCeKDtW9ubx7ssuqO9CfcpZ3VHRyBwqB6UHzz7tWJiyLFVGNOBUxaNOY2Ik3JtVIWdkujmkBuelDOSjVGMAOziSRzIgB6hYdT8iRUMeSfgJLJ7pysLxIOaRFmx90r4WlKNpJy7drmk2F734cKuKrborBLCzg7P6ewbvsZCp/KP0je0fLIF2IEbO7UgiYzJGHOWQDuzmljk22c/5XMzqnGbUi8Wf+OWvUnL+sQZCPssTMeFUudolQlo4UvyNcb2WK+7i2mUaYMKRERv1pvCZB6H0Z2KS6l2EkTsP9ey6D4WQCIrPLFo+OgXBEtEw2/7DpzNXfpS+0VXSnI//Ds1yLuBntTVo8e2SqT/0dKJoD7m+LAQZgldnxscUyucVLUHXv3yeVlryCzGv/MgMaxssVxyjOErA3GR9eiPQJpEZhYCDIeS8xv5Qeti5nab5+dQfg9P1WYIqBXSJxKAEmMAFHC3z8EoLo=
