env:
  global:
    - VERSION="1.0"
    - BRANCH="bug_fixed"

services:
  - docker

before_install:
  - docker build -t "$DOCKER_ID"/bns-relaese:$VERSION .

script:
  - docker run
    -e DB_HOST="$DB_HOST"
    -e DB_NAME="$DB_NAME"
    -e DB_USER="$DB_USER"
    -e DB_PASSWORD="$DB_PASSWORD"
    -e DB_PORT="$DB_PORT"
    -e AWS_STORAGE_BUCKET_NAME="$AWS_STORAGE_BUCKET_NAME"
    -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    --rm "$DOCKER_ID"/bns-relaese:$VERSION
    python3.6 manage.py test category

after_success:
  - echo "$DOCKER_PASSWPRD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push "$DOCKER_ID"/bns-relaese:$VERSION

before_deploy:
  - sed -i='' -e "s/<DOCKER_ID>/$DOCKER_ID/" -e "s/<TAG>/$VERSION/" Dockerrun.aws.json
  - mkdir -p archive
  - cp ./Dockerrun.aws.json ./archive/Dockerrun.aws.json
  - cp -r ./.ebextensions archive/.ebextensions
  - cd archive
  - ls -al
  - zip -r archive.zip Dockerrun.aws.json .ebextensions

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "ap-northeast-2"
  app: "BuynSell"
  env: "Buynsell-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-109247251546"
  bucket_path: "BuynSell-env"
  on:
    branch: $BRANCH
  zip_file: archive.zip
  skip_cleanup: true

after_deploy:
  - echo "EB $VERSION버전 배포 진행중 ..."

notifications:
  slack:
    secure: $SLACK_ENV
