# Generated by Django 2.1 on 2019-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerask',
            name='ask_category',
        ),
        migrations.RemoveField(
            model_name='customerfaq',
            name='faq_category',
        ),
        migrations.AddField(
            model_name='customerask',
            name='ask_post',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfaq',
            name='faq_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
