# Generated by Django 2.1 on 2019-06-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190608_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_category', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='customerask',
            name='ask_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfaq',
            name='faq_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerCategory'),
            preserve_default=False,
        ),
    ]
