# Generated by Django 2.1 on 2019-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190608_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerask',
            name='ask_comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
