# Generated by Django 2.1 on 2019-06-08 16:03

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerask_ask_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=40)),
                ('notice_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
