# Generated by Django 2.1 on 2019-06-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('reserv', '결제예약'), ('ready', '미결제'), ('cancelled', '결제취소'), ('paid', '결제완료'), ('failed', '결제실패')], db_index=True, default='ready', max_length=9),
        ),
    ]
