# Generated by Django 2.1 on 2019-07-13 04:57

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패'), ('reserv', '거래예약'), ('success', '거래완료')], db_index=True, default='ready', max_length=9),
        ),
    ]
