# Generated by Django 2.1 on 2019-07-04 16:55

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='item_img/2019-07-04'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패'), ('reserv', '구매예약'), ('success', '구매완료')], db_index=True, default='ready', max_length=9),
        ),
    ]
