# Generated by Django 2.1 on 2019-06-02 10:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190529_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog/post'),
        ),
    ]
