# Generated by Django 2.1 on 2019-06-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190602_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcomment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.SubCategory'),
        ),
    ]
