# Generated by Django 2.1 on 2019-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_addr',
            field=models.CharField(default='wef', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(default='wef@few.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default='wef', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_postcode',
            field=models.CharField(default=324, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_tel',
            field=models.CharField(default=23, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', '미결제'), ('faild', '결제실패'), ('paid', '결제완료'), ('cancelled', '결제취소')], db_index=True, default='ready', max_length=9),
        ),
    ]
