# Generated by Django 2.1 on 2019-06-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190604_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='trade.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('faild', '결제실패'), ('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소')], db_index=True, default='ready', max_length=9),
        ),
    ]
