# Generated by Django 2.1 on 2019-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20190604_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('a', 'A급'), ('c', 'C급 이하'), ('b', 'B급'), ('s', 'S급')], default='a', max_length=9),
        ),
        migrations.AddField(
            model_name='item',
            name='pay_status',
            field=models.CharField(choices=[('reservation', '예약'), ('sale_complete', '판매완료'), ('ready', '재고있음')], db_index=True, default='ready', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', '결제완료'), ('failed', '결제실패'), ('cancelled', '결제취소'), ('ready', '미결제')], db_index=True, default='ready', max_length=9),
        ),
    ]
