# Generated by Django 2.1 on 2019-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20190605_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('c', 'C급 이하'), ('b', 'B급'), ('a', 'A급'), ('s', 'S급')], default='a', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='pay_status',
            field=models.CharField(choices=[('reservation', '예약'), ('sale_complete', '판매완료'), ('ready', '재고있음')], db_index=True, default='ready', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('failed', '결제실패'), ('cancelled', '결제취소')], db_index=True, default='ready', max_length=9),
        ),
    ]
