# Generated by Django 2.1 on 2019-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20190605_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('a', 'A급'), ('c', 'C급 이하'), ('b', 'B급'), ('s', 'S급')], default='a', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='pay_status',
            field=models.CharField(choices=[('reservation', '예약'), ('ready', '재고있음'), ('sale_complete', '판매완료')], db_index=True, default='ready', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', '결제완료'), ('failed', '결제실패'), ('ready', '미결제'), ('cancelled', '결제취소')], db_index=True, default='ready', max_length=9),
        ),
    ]
