# Generated by Django 2.1 on 2019-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='detail_address',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='post_code',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
