# Generated by Django 2.1 on 2019-06-04 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190528_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_num',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='정확한 연락처를 적어주세요.', regex='^0\\d{8,10}$')]),
        ),
    ]
