# Generated by Django 2.1 on 2019-05-28 01:57

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_num',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nic_name',
            field=models.CharField(max_length=10, unique=True, validators=[accounts.models.id_validate]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='정확한 연락처를 적어주세요.', regex='^0\\d{10,11}$')]),
        ),
    ]
